import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { AdviceResponse, AdviceBullet } from '../types/advice'

export function generateAdvicePdf(advice: AdviceResponse, dateRange: string): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // Title
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Trade Nexus Report', pageWidth / 2, y, { align: 'center' })
  y += 8

  // Date range
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`Analysis Period: ${dateRange}`, pageWidth / 2, y, { align: 'center' })
  y += 6

  // Overall Score
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text(`Overall Grade: ${advice.overall_score}`, pageWidth / 2, y, { align: 'center' })
  y += 4

  // Divider
  doc.setDrawColor(200, 200, 200)
  doc.line(14, y, pageWidth - 14, y)
  y += 8

  // Executive Summary
  if (advice.summary) {
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text('Executive Summary', 14, y)
    y += 7
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    const summaryLines = doc.splitTextToSize(advice.summary, pageWidth - 28)
    doc.text(summaryLines, 14, y)
    y += summaryLines.length * 5 + 8
  }

  // Key Metrics Table
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('Key Metrics', 14, y)
  y += 2

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Win Rate', `${advice.metrics.win_rate}%`],
      ['Risk-Reward Ratio', `${advice.metrics.rr_ratio}:1`],
      ['Kelly Criterion', `${advice.kelly_pct}% (Half: ${advice.half_kelly_pct}%)`],
      ['Win/Loss Asymmetry', `${advice.metrics.asymmetry}x`],
      ['Realized P&L', `Rs ${advice.metrics.realized_pnl.toLocaleString('en-IN')}`],
      ['Net After Charges', `Rs ${advice.metrics.net_after_charges.toLocaleString('en-IN')}`],
      ['Total Charges', `Rs ${advice.metrics.total_charges.toLocaleString('en-IN')}`],
      ['Charges % of P&L', `${advice.metrics.charges_pct}%`],
      ['Concentration (Top 5)', `${advice.metrics.concentration_pct}%`],
      ['Symbols Traded', `${advice.metrics.symbols_traded}`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [235, 59, 59], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 0: { fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  })

  y = (doc as ReturnType<typeof autoTable> & { lastAutoTable: { finalY: number } } & jsPDF).lastAutoTable?.finalY
    ?? (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY
    ?? y + 80
  y += 10

  // Helper to render bullet sections
  const renderBullets = (title: string, bullets: AdviceBullet[]) => {
    if (y > 255) { doc.addPage(); y = 20 }
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0, 0, 0)
    doc.text(title, 14, y)
    y += 7
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    bullets.forEach((b, i) => {
      if (y > 275) { doc.addPage(); y = 20 }
      const text = `${i + 1}. ${b.text}`
      const lines = doc.splitTextToSize(text, pageWidth - 28)
      doc.text(lines, 14, y)
      y += lines.length * 4.5 + 3
    })
    y += 5
  }

  renderBullets('Strengths', advice.strengths)
  renderBullets('Weaknesses', advice.weaknesses)
  renderBullets('Recommendations', advice.recommendations)

  // Pareto Insight
  if (y > 260) { doc.addPage(); y = 20 }
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(0, 0, 0)
  doc.text('Pareto Insight (80/20 Rule)', 14, y)
  y += 7
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(40, 40, 40)
  const paretoLines = doc.splitTextToSize(advice.pareto_insight, pageWidth - 28)
  doc.text(paretoLines, 14, y)
  y += paretoLines.length * 4.5 + 10

  // Footer
  if (y > 275) { doc.addPage(); y = 20 }
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Trade Nexus — F&O P&L Analytics Dashboard', pageWidth / 2, 285, { align: 'center' })

  doc.save('trade-nexus-report.pdf')
}
